# -*- coding: utf-8 -*-
"""АнализДанных56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZHG8MNMm2t58bwjukpNloEGkeXj-2Yb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.metrics import pairwise_distances

df = pd.read_csv("customers.csv")

df

DROP_COLS = ["Row", "CustomerId"]

feature_cols = [col for col in df.select_dtypes(include=np.number).columns if col not in DROP_COLS]

print("Признаки для кластеризации:")
print(feature_cols)

imputer = SimpleImputer(strategy="median")

X_raw = pd.DataFrame(imputer.fit_transform(df[feature_cols]),columns=feature_cols,index=df.index)

scaler = StandardScaler()

X = scaler.fit_transform(X_raw)

display(X_raw.head())

def kmedoids(X, k, max_iter=100):
    n = len(X)

    # случайные начальные медоиды
    medoids = np.random.choice(n, k, replace=False)

    # расстояния между всеми точками
    D = pairwise_distances(X)

    for _ in range(max_iter):
        # определяем кластер каждой точки
        labels = np.argmin(D[:, medoids], axis=1)

        new_medoids = medoids.copy()

        for i in range(k):
            points = np.where(labels == i)[0]

            if len(points) == 0:
                continue

            # выбираем точку с минимальной суммой
            # расстояний до остальных точек кластера
            distances = D[np.ix_(points, points)]
            new_medoids[i] = points[np.argmin(distances.sum(axis=1))]

        if np.array_equal(medoids, new_medoids):
            break

        medoids = new_medoids

    labels = np.argmin(D[:, medoids], axis=1)

    # ошибка кластеризации
    error = np.sum(D[np.arange(n), medoids[labels]] ** 2)

    return labels, medoids, error

k = 4

# K-Means
model = KMeans(n_clusters=k, random_state=42, n_init=10)
labels_kmeans = model.fit_predict(X)

print("Ошибка K-Means:", model.inertia_)
print("Кластеры:")
print(labels_kmeans)

np.random.seed(42)

labels_kmedoids, medoids, error_kmedoids = kmedoids(X, k)

print("Ошибка K-Medoids:", error_kmedoids)
print("Кластеры:")
print(labels_kmedoids)

pca = PCA(n_components=2)
X_2d = pca.fit_transform(X)

plt.figure(figsize=(8, 5))

plt.scatter(X_2d[:, 0],X_2d[:, 1],c=labels_kmeans,cmap="tab10")

plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("K-Means")

plt.show()

plt.figure(figsize=(8, 5))

plt.scatter(X_2d[:, 0],X_2d[:, 1],c=labels_kmedoids,cmap="tab10")

plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("K-Medoids")

plt.show()

ks = range(3, 10)

errors_kmeans = []
errors_kmedoids = []

for k in ks:
    # K-Means
    model = KMeans(n_clusters=k,random_state=42,n_init=10)

    model.fit(X)
    errors_kmeans.append(model.inertia_)

    # K-Medoids
    np.random.seed(42)

    labels, medoids, error = kmedoids(X, k)
    errors_kmedoids.append(error)

plt.figure(figsize=(8, 5))

plt.plot(ks, errors_kmeans, marker="o", label="K-Means")
plt.plot(ks, errors_kmedoids, marker="o", label="K-Medoids")

plt.xlabel("k")
plt.ylabel("Ошибка")
plt.title("Зависимость ошибки от k")

plt.legend()
plt.grid()

plt.show()

def add_noise(X, percent):
    X_noise = X.copy()

    n = int(len(X) * percent / 100)

    # какие объекты будем портить
    rows = np.random.choice(len(X),n,replace=False)

    for row in rows:
        # изменить от 1 до 3 координат
        count = np.random.randint(1, 4)

        cols = np.random.choice(X.shape[1],count,replace=False)

        # случайно прибавляем числа
        X_noise[row, cols] += np.random.uniform(-2,2,count)

    return X_noise

noise_levels = [1, 3, 5, 10]

results = []

for noise in noise_levels:
    np.random.seed(42)

    X_noise = add_noise(X, noise)

    for k in range(3, 10):
        # K-Means
        model = KMeans(n_clusters=k,random_state=42,n_init=10)

        model.fit(X_noise)

        results.append([noise,k,"K-Means",model.inertia_])

        # K-Medoids
        np.random.seed(42)

        labels, medoids, error = kmedoids(X_noise,k)

        results.append([noise,k,"K-Medoids",error])

results = pd.DataFrame(results,columns=["noise", "k", "method", "error"])

results

plt.figure(figsize=(8, 5))

for noise in noise_levels:
    data = results[(results["noise"] == noise) &(results["method"] == "K-Means")]

    plt.plot(data["k"],data["error"],marker="o",label=f"{noise}% шума")

plt.xlabel("k")
plt.ylabel("Ошибка")
plt.title("K-Means")

plt.legend()
plt.grid()

plt.show()

plt.figure(figsize=(8, 5))

for noise in noise_levels:
    data = results[(results["noise"] == noise) &(results["method"] == "K-Medoids")]

    plt.plot(data["k"],data["error"],marker="o",label=f"{noise}% шума")

plt.xlabel("k")
plt.ylabel("Ошибка")
plt.title("K-Medoids")

plt.legend()
plt.grid()

plt.show()

"""# Лабораторная работа 6"""

from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
import matplotlib.pyplot as plt
k = 4

def hierarchical_clustering(X, method):
    Z = linkage(X,method=method,metric="euclidean")

    # Получаем k кластеров
    labels = fcluster(Z,t=k,criterion="maxclust") - 1

    # Дендрограмма
    plt.figure(figsize=(12, 6))

    dendrogram(Z)

    plt.title(f"Иерархическая кластеризация: {method}")
    plt.xlabel("Объекты")
    plt.ylabel("Расстояние")

    plt.show()

    return labels

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_2d = pca.fit_transform(X_scaled)

fig, axes = plt.subplots(1,2,figsize=(12, 5))

# Предыдущая кластеризация K-Means
axes[0].scatter(X_2d[:, 0],X_2d[:, 1],c=labels_kmeans,cmap="tab10")

axes[0].set_title("K-Means")
axes[0].set_xlabel("PCA 1")
axes[0].set_ylabel("PCA 2")


# Иерархическая кластеризация
axes[1].scatter(X_2d[:, 0],X_2d[:, 1],c=labels_ward,cmap="tab10")

axes[1].set_title("Иерархическая, Ward")
axes[1].set_xlabel("PCA 1")
axes[1].set_ylabel("PCA 2")


plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1,2,figsize=(12, 5))

axes[0].scatter(X_2d[:, 0],X_2d[:, 1],c=labels_kmedoids,cmap="tab10")

axes[0].set_title("K-Medoids")
axes[0].set_xlabel("PCA 1")
axes[0].set_ylabel("PCA 2")


axes[1].scatter(X_2d[:, 0],X_2d[:, 1],c=labels_ward,cmap="tab10")

axes[1].set_title("Иерархическая, Ward")
axes[1].set_xlabel("PCA 1")
axes[1].set_ylabel("PCA 2")


plt.tight_layout()
plt.show()

methods = ["single","complete","average","ward"]

labels_hierarchical = {}

for method in methods:labels_hierarchical[method] = hierarchical_clustering(X_scaled,method)

fig, axes = plt.subplots(2,2,figsize=(12, 10))

axes = axes.ravel()

for ax, method in zip(axes, methods):

    labels = labels_hierarchical[method]

    ax.scatter(X_2d[:, 0],X_2d[:, 1],c=labels,cmap="tab10")

    ax.set_title(method)
    ax.set_xlabel("PCA 1")
    ax.set_ylabel("PCA 2")

plt.tight_layout()
plt.show()